/** Provinces RDC (26) */
export const RDC_PROVINCES: { code: string; label: string }[] = [
  { code: "KN", label: "Kinshasa" },
  { code: "KC", label: "Kongo-Central" },
  { code: "KW", label: "Kwango" },
  { code: "KL", label: "Kwilu" },
  { code: "MN", label: "Mai-Ndombe" },
  { code: "KS", label: "Kasaï" },
  { code: "KE", label: "Kasaï-Central" },
  { code: "KO", label: "Kasaï-Oriental" },
  { code: "LO", label: "Lomami" },
  { code: "SA", label: "Sankuru" },
  { code: "MA", label: "Maniema" },
  { code: "SK", label: "Sud-Kivu" },
  { code: "NK", label: "Nord-Kivu" },
  { code: "IT", label: "Ituri" },
  { code: "HU", label: "Haut-Uele" },
  { code: "TS", label: "Tshopo" },
  { code: "BU", label: "Bas-Uele" },
  { code: "MO", label: "Mongala" },
  { code: "NU", label: "Nord-Ubangi" },
  { code: "SU", label: "Sud-Ubangi" },
  { code: "EQ", label: "Équateur" },
  { code: "TU", label: "Tshuapa" },
  { code: "TA", label: "Tanganyika" },
  { code: "HL", label: "Haut-Lomami" },
  { code: "LU", label: "Lualaba" },
  { code: "HK", label: "Haut-Katanga" },
];

/** Liste pays pour formulaires courrier */
export const COUNTRIES = [
  "Afghanistan", "Afrique du Sud", "Algérie", "Allemagne", "Angola", "Arabie saoudite",
  "Argentine", "Belgique", "Bénin", "Botswana", "Brésil", "Burkina Faso", "Burundi",
  "Cameroun", "Canada", "Centrafrique", "Chine", "Comores", "Congo", "Côte d'Ivoire",
  "Djibouti", "Égypte", "Émirats arabes unis", "Espagne", "Éthiopie", "France",
  "Gabon", "Ghana", "Guinée", "Guinée-Bissau", "Guinée équatoriale", "Inde",
  "Italie", "Japon", "Kenya", "Liban", "Libye", "Madagascar", "Malawi", "Mali",
  "Maroc", "Mauritanie", "Mozambique", "Namibie", "Niger", "Nigeria", "Ouganda",
  "Pays-Bas", "Portugal", "République démocratique du Congo", "République du Congo",
  "Rwanda", "Sénégal", "Sierra Leone", "Soudan", "Soudan du Sud", "Tanzanie", "Tchad",
  "Togo", "Tunisie", "Turquie", "États-Unis", "Royaume-Uni", "Zambie", "Zimbabwe",
  "Autre",
] as const;
