project_id = "rpsoucyybuudhwvsktah"

[functions.ai-assistant]
verify_jwt = false

[functions.sla-checker]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.sync-users]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false